# Generated by Django 4.1.7 on 2023-03-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_alter_counter_cur_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='is_serving',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='counter',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
