# Generated by Django 4.1.7 on 2023-03-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_ticket_date_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='is_serving',
        ),
    ]
