# Generated by Django 4.1.7 on 2023-03-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_remove_counter_is_serving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='cur_num',
            field=models.IntegerField(default=0),
        ),
    ]
