# Generated by Django 4.1.7 on 2023-03-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_alter_counter_cur_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='cur_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
